// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class AuditLog
{
    public int AuditId { get; set; }

    public string TableName { get; set; }

    public int? RecordId { get; set; }

    public string ActionType { get; set; }

    public string OldData { get; set; }

    public string NewData { get; set; }

    public int? ActionBy { get; set; }

    public DateTime? ActionDate { get; set; }
}