// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class BookingCancellation
{
    public int CancellationId { get; set; }

    public int BookingId { get; set; }

    public DateTime? CancellationDate { get; set; }

    public string Reason { get; set; }

    public decimal? CancellationCharge { get; set; }

    public decimal? RefundAmount { get; set; }

    public virtual Booking Booking { get; set; }
}