// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class BookingDiscount
{
    public int BookingDiscountId { get; set; }

    public int BookingId { get; set; }

    public int DiscountId { get; set; }

    public decimal? AppliedAmount { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Discount Discount { get; set; }
}