// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class BookingService
{
    public int BookingServiceId { get; set; }

    public int BookingId { get; set; }

    public int ServiceId { get; set; }

    public int? Quantity { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Gstpercent { get; set; }

    public decimal? Amount { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Service Service { get; set; }
}