// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int BranchId { get; set; }

    public int CustomerId { get; set; }

    public int? EventTypeId { get; set; }

    public int? PackageId { get; set; }

    public DateOnly EventDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BookingCancellation> BookingCancellations { get; set; } = new List<BookingCancellation>();

    public virtual ICollection<BookingDiscount> BookingDiscounts { get; set; } = new List<BookingDiscount>();

    public virtual ICollection<BookingService> BookingServices { get; set; } = new List<BookingService>();

    public virtual Branch Branch { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<DamagePenalty> DamagePenalties { get; set; } = new List<DamagePenalty>();

    public virtual EventType EventType { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual Package Package { get; set; }

    public virtual ICollection<Refund> Refunds { get; set; } = new List<Refund>();
}