// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Discount
{
    public int DiscountId { get; set; }

    public int BranchId { get; set; }

    public string DiscountName { get; set; }

    public string DiscountType { get; set; }

    public decimal? Value { get; set; }

    public DateOnly? ValidFrom { get; set; }

    public DateOnly? ValidTo { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BookingDiscount> BookingDiscounts { get; set; } = new List<BookingDiscount>();

    public virtual Branch Branch { get; set; }
}