// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class EventType
{
    public int EventTypeId { get; set; }

    public string EventName { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}