// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class ExpenseCategory
{
    public int ExpenseCategoryId { get; set; }

    public int BranchId { get; set; }

    public string CategoryName { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();
}