// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Expense
{
    public int ExpenseId { get; set; }

    public int BranchId { get; set; }

    public int ExpenseCategoryId { get; set; }

    public DateOnly ExpenseDate { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMode { get; set; }

    public string ReferenceNo { get; set; }

    public string Remarks { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ExpenseCategory ExpenseCategory { get; set; }
}