// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Hall
{
    public int HallId { get; set; }

    public int BranchId { get; set; }

    public string HallName { get; set; }

    public int? Capacity { get; set; }

    public virtual Branch Branch { get; set; }
}