// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public int BookingId { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? Gstamount { get; set; }

    public decimal? GrandTotal { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}