// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Item
{
    public int ItemId { get; set; }

    public int BranchId { get; set; }

    public int? CategoryId { get; set; }

    public string ItemName { get; set; }

    public string Unit { get; set; }

    public int? MinStockLevel { get; set; }

    public bool? IsActive { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ItemCategory Category { get; set; }

    public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; } = new List<PurchaseDetail>();

    public virtual ICollection<StockLedger> StockLedgers { get; set; } = new List<StockLedger>();
}