// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class ItemCategory
{
    public int CategoryId { get; set; }

    public int BranchId { get; set; }

    public string CategoryName { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}