// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Offer
{
    public int OfferId { get; set; }

    public int BranchId { get; set; }

    public string OfferName { get; set; }

    public string OfferType { get; set; }

    public string Description { get; set; }

    public DateOnly? ValidFrom { get; set; }

    public DateOnly? ValidTo { get; set; }

    public bool? IsActive { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<OfferMapping> OfferMappings { get; set; } = new List<OfferMapping>();
}