// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class OfferMapping
{
    public int OfferMappingId { get; set; }

    public int OfferId { get; set; }

    public int RefId { get; set; }

    public string RefType { get; set; }

    public virtual Offer Offer { get; set; }
}