// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class PackageService
{
    public int PackageServiceId { get; set; }

    public int PackageId { get; set; }

    public int ServiceId { get; set; }

    public virtual Package Package { get; set; }

    public virtual Service Service { get; set; }
}