// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QuizServer.Models;

public partial class PerfectGardenAppDBContext : DbContext
{
    public PerfectGardenAppDBContext(DbContextOptions<PerfectGardenAppDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingCancellation> BookingCancellations { get; set; }

    public virtual DbSet<BookingDiscount> BookingDiscounts { get; set; }

    public virtual DbSet<BookingService> BookingServices { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<DamagePenalty> DamagePenalties { get; set; }

    public virtual DbSet<Discount> Discounts { get; set; }

    public virtual DbSet<EventType> EventTypes { get; set; }

    public virtual DbSet<Expense> Expenses { get; set; }

    public virtual DbSet<ExpenseCategory> ExpenseCategories { get; set; }

    public virtual DbSet<Hall> Halls { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<ItemCategory> ItemCategories { get; set; }

    public virtual DbSet<Offer> Offers { get; set; }

    public virtual DbSet<OfferMapping> OfferMappings { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<PackageService> PackageServices { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }

    public virtual DbSet<Refund> Refunds { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }

    public virtual DbSet<ServicePricing> ServicePricings { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    public virtual DbSet<StaffAttendance> StaffAttendances { get; set; }

    public virtual DbSet<StaffPayment> StaffPayments { get; set; }

    public virtual DbSet<StockLedger> StockLedgers { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("perfect_garden");

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditId).HasName("PK__AuditLog__A17F2398B1D15840");

            entity.ToTable("AuditLog");

            entity.HasIndex(e => e.ActionDate, "IX_AuditLog_Date");

            entity.HasIndex(e => new { e.TableName, e.RecordId }, "IX_AuditLog_Table_Record");

            entity.Property(e => e.ActionDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.ActionType).HasMaxLength(50);
            entity.Property(e => e.TableName).HasMaxLength(100);
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Booking__73951AEDB2DD180B");

            entity.ToTable("Booking");

            entity.HasIndex(e => new { e.BranchId, e.EventDate }, "IX_Booking_Branch_EventDate");

            entity.Property(e => e.AdvanceAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Booked");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Branch).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking__BranchI__498EEC8D");

            entity.HasOne(d => d.Customer).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Booking__Custome__4A8310C6");

            entity.HasOne(d => d.EventType).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.EventTypeId)
                .HasConstraintName("FK__Booking__EventTy__4B7734FF");

            entity.HasOne(d => d.Package).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK__Booking__Package__4C6B5938");
        });

        modelBuilder.Entity<BookingCancellation>(entity =>
        {
            entity.HasKey(e => e.CancellationId).HasName("PK__BookingC__6A2D9A3AF8CA8594");

            entity.ToTable("BookingCancellation");

            entity.Property(e => e.CancellationCharge).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CancellationDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Reason).HasMaxLength(300);
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingCancellations)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingCa__Booki__7A3223E8");
        });

        modelBuilder.Entity<BookingDiscount>(entity =>
        {
            entity.HasKey(e => e.BookingDiscountId).HasName("PK__BookingD__30250668B2928215");

            entity.ToTable("BookingDiscount");

            entity.Property(e => e.AppliedAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingDiscounts)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingDi__Booki__6EC0713C");

            entity.HasOne(d => d.Discount).WithMany(p => p.BookingDiscounts)
                .HasForeignKey(d => d.DiscountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingDi__Disco__6FB49575");
        });

        modelBuilder.Entity<BookingService>(entity =>
        {
            entity.HasKey(e => e.BookingServiceId).HasName("PK__BookingS__43F55CB151F2F112");

            entity.ToTable("BookingService");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Gstpercent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("GSTPercent");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingServices)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingSe__Booki__4F47C5E3");

            entity.HasOne(d => d.Service).WithMany(p => p.BookingServices)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookingSe__Servi__503BEA1C");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.BranchId).HasName("PK__Branch__A1682FC524E5A043");

            entity.ToTable("Branch");

            entity.Property(e => e.Address).HasMaxLength(300);
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Gstnumber)
                .HasMaxLength(20)
                .HasColumnName("GSTNumber");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.State).HasMaxLength(100);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D8CC203B31");

            entity.ToTable("Customer");

            entity.HasIndex(e => e.Mobile, "IX_Customer_Mobile");

            entity.Property(e => e.Address).HasMaxLength(300);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FullName).HasMaxLength(150);
            entity.Property(e => e.Mobile).HasMaxLength(15);
        });

        modelBuilder.Entity<DamagePenalty>(entity =>
        {
            entity.HasKey(e => e.DamageId).HasName("PK__DamagePe__8A0F2162ABFBDC05");

            entity.ToTable("DamagePenalty");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Description).HasMaxLength(300);

            entity.HasOne(d => d.Booking).WithMany(p => p.DamagePenalties)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DamagePen__Booki__7D0E9093");
        });

        modelBuilder.Entity<Discount>(entity =>
        {
            entity.HasKey(e => e.DiscountId).HasName("PK__Discount__E43F6D960109EA3D");

            entity.ToTable("Discount");

            entity.Property(e => e.DiscountName).HasMaxLength(150);
            entity.Property(e => e.DiscountType).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Value).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Branch).WithMany(p => p.Discounts)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Discount__Branch__6BE40491");
        });

        modelBuilder.Entity<EventType>(entity =>
        {
            entity.HasKey(e => e.EventTypeId).HasName("PK__EventTyp__A9216B3FFB7BA080");

            entity.ToTable("EventType");

            entity.Property(e => e.EventName).HasMaxLength(100);
        });

        modelBuilder.Entity<Expense>(entity =>
        {
            entity.HasKey(e => e.ExpenseId).HasName("PK__Expense__1445CFD3B8153102");

            entity.ToTable("Expense");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentMode).HasMaxLength(50);
            entity.Property(e => e.ReferenceNo).HasMaxLength(100);
            entity.Property(e => e.Remarks).HasMaxLength(300);

            entity.HasOne(d => d.Branch).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Expense__BranchI__5D95E53A");

            entity.HasOne(d => d.ExpenseCategory).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.ExpenseCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Expense__Expense__5E8A0973");
        });

        modelBuilder.Entity<ExpenseCategory>(entity =>
        {
            entity.HasKey(e => e.ExpenseCategoryId).HasName("PK__ExpenseC__9C2C63F889139E5B");

            entity.ToTable("ExpenseCategory");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.Branch).WithMany(p => p.ExpenseCategories)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExpenseCa__Branc__5AB9788F");
        });

        modelBuilder.Entity<Hall>(entity =>
        {
            entity.HasKey(e => e.HallId).HasName("PK__Hall__7E60E21499CF6E44");

            entity.ToTable("Hall");

            entity.Property(e => e.HallName).HasMaxLength(150);

            entity.HasOne(d => d.Branch).WithMany(p => p.Halls)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Hall__BranchId__0880433F");
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.InvoiceId).HasName("PK__Invoice__D796AAB536C74F13");

            entity.ToTable("Invoice");

            entity.Property(e => e.GrandTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Gstamount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("GSTAmount");
            entity.Property(e => e.InvoiceDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Invoice__Booking__540C7B00");
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Item__727E838BECF5905F");

            entity.ToTable("Item");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.MinStockLevel).HasDefaultValue(0);
            entity.Property(e => e.Unit).HasMaxLength(50);

            entity.HasOne(d => d.Branch).WithMany(p => p.Items)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Item__BranchId__1EA48E88");

            entity.HasOne(d => d.Category).WithMany(p => p.Items)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__Item__CategoryId__1F98B2C1");
        });

        modelBuilder.Entity<ItemCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__ItemCate__19093A0B58A1CC53");

            entity.ToTable("ItemCategory");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Branch).WithMany(p => p.ItemCategories)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemCateg__Branc__19DFD96B");
        });

        modelBuilder.Entity<Offer>(entity =>
        {
            entity.HasKey(e => e.OfferId).HasName("PK__Offer__8EBCF091966EC96E");

            entity.ToTable("Offer");

            entity.Property(e => e.Description).HasMaxLength(300);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.OfferName).HasMaxLength(150);
            entity.Property(e => e.OfferType).HasMaxLength(50);

            entity.HasOne(d => d.Branch).WithMany(p => p.Offers)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Offer__BranchId__73852659");
        });

        modelBuilder.Entity<OfferMapping>(entity =>
        {
            entity.HasKey(e => e.OfferMappingId).HasName("PK__OfferMap__F9A28211C1FD2052");

            entity.ToTable("OfferMapping");

            entity.Property(e => e.RefType).HasMaxLength(50);

            entity.HasOne(d => d.Offer).WithMany(p => p.OfferMappings)
                .HasForeignKey(d => d.OfferId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OfferMapp__Offer__76619304");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.PackageId).HasName("PK__Package__322035CC6086F712");

            entity.ToTable("Package");

            entity.Property(e => e.Gstpercent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("GSTPercent");
            entity.Property(e => e.PackageName).HasMaxLength(150);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Branch).WithMany(p => p.Packages)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Package__BranchI__3F115E1A");
        });

        modelBuilder.Entity<PackageService>(entity =>
        {
            entity.HasKey(e => e.PackageServiceId).HasName("PK__PackageS__5EAFC23056DD36D0");

            entity.ToTable("PackageService");

            entity.HasOne(d => d.Package).WithMany(p => p.PackageServices)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PackageSe__Packa__41EDCAC5");

            entity.HasOne(d => d.Service).WithMany(p => p.PackageServices)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PackageSe__Servi__42E1EEFE");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A3825AF3504");

            entity.ToTable("Payment");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.PaymentMode).HasMaxLength(50);

            entity.HasOne(d => d.Invoice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.InvoiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__Invoice__57DD0BE4");
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.PurchaseId).HasName("PK__Purchase__6B0A6BBE3DBC1405");

            entity.ToTable("Purchase");

            entity.Property(e => e.Gstamount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("GSTAmount");
            entity.Property(e => e.InvoiceNo).HasMaxLength(100);
            entity.Property(e => e.SubTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Branch).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Purchase__Branch__2645B050");

            entity.HasOne(d => d.Supplier).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Purchase__Suppli__2739D489");
        });

        modelBuilder.Entity<PurchaseDetail>(entity =>
        {
            entity.HasKey(e => e.PurchaseDetailId).HasName("PK__Purchase__88C328B523F80468");

            entity.ToTable("PurchaseDetail");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Item).WithMany(p => p.PurchaseDetails)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PurchaseD__ItemI__2B0A656D");

            entity.HasOne(d => d.Purchase).WithMany(p => p.PurchaseDetails)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PurchaseD__Purch__2A164134");
        });

        modelBuilder.Entity<Refund>(entity =>
        {
            entity.HasKey(e => e.RefundId).HasName("PK__Refund__725AB9203926DF60");

            entity.ToTable("Refund");

            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RefundDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.RefundMode).HasMaxLength(50);

            entity.HasOne(d => d.Booking).WithMany(p => p.Refunds)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Refund__BookingI__00DF2177");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("PK__Service__C51BB00AD3CA50AB");

            entity.ToTable("Service");

            entity.Property(e => e.BasePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ChargeType).HasMaxLength(50);
            entity.Property(e => e.DayPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Gstpercent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("GSTPercent");
            entity.Property(e => e.HourPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ServiceName).HasMaxLength(150);

            entity.HasOne(d => d.Branch).WithMany(p => p.Services)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Service__BranchI__3864608B");

            entity.HasOne(d => d.ServiceCategory).WithMany(p => p.Services)
                .HasForeignKey(d => d.ServiceCategoryId)
                .HasConstraintName("FK__Service__Service__395884C4");
        });

        modelBuilder.Entity<ServiceCategory>(entity =>
        {
            entity.HasKey(e => e.ServiceCategoryId).HasName("PK__ServiceC__E4CC7EAA4AA8CD9B");

            entity.ToTable("ServiceCategory");

            entity.Property(e => e.CategoryName).HasMaxLength(100);
        });

        modelBuilder.Entity<ServicePricing>(entity =>
        {
            entity.HasKey(e => e.PricingId).HasName("PK__ServiceP__EC306B12E7C2AA04");

            entity.ToTable("ServicePricing");

            entity.Property(e => e.DayType).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Service).WithMany(p => p.ServicePricings)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ServicePr__Servi__3C34F16F");
        });

        modelBuilder.Entity<Staff>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("PK__Staff__96D4AB17D09251B1");

            entity.Property(e => e.Address).HasMaxLength(300);
            entity.Property(e => e.FullName).HasMaxLength(150);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Mobile).HasMaxLength(15);
            entity.Property(e => e.RoleName).HasMaxLength(100);
            entity.Property(e => e.SalaryAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SalaryType).HasMaxLength(50);

            entity.HasOne(d => d.Branch).WithMany(p => p.Staff)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Staff__BranchId__625A9A57");
        });

        modelBuilder.Entity<StaffAttendance>(entity =>
        {
            entity.HasKey(e => e.AttendanceId).HasName("PK__StaffAtt__8B69261C1017BD48");

            entity.ToTable("StaffAttendance");

            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Staff).WithMany(p => p.StaffAttendances)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StaffAtte__Staff__65370702");
        });

        modelBuilder.Entity<StaffPayment>(entity =>
        {
            entity.HasKey(e => e.StaffPaymentId).HasName("PK__StaffPay__2D07B993D861E576");

            entity.ToTable("StaffPayment");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Remarks).HasMaxLength(300);

            entity.HasOne(d => d.Staff).WithMany(p => p.StaffPayments)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StaffPaym__Staff__681373AD");
        });

        modelBuilder.Entity<StockLedger>(entity =>
        {
            entity.HasKey(e => e.StockLedgerId).HasName("PK__StockLed__3E88172B219806E1");

            entity.ToTable("StockLedger");

            entity.Property(e => e.QuantityIn)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.QuantityOut)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RefType).HasMaxLength(50);
            entity.Property(e => e.TransactionDate).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.Branch).WithMany(p => p.StockLedgers)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockLedg__Branc__30C33EC3");

            entity.HasOne(d => d.Item).WithMany(p => p.StockLedgers)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StockLedg__ItemI__31B762FC");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(e => e.SupplierId).HasName("PK__Supplier__4BE666B452A87174");

            entity.ToTable("Supplier");

            entity.Property(e => e.Address).HasMaxLength(300);
            entity.Property(e => e.Email).HasMaxLength(15);
            entity.Property(e => e.Gstnumber)
                .HasMaxLength(20)
                .HasColumnName("GSTNumber");
            entity.Property(e => e.Mobile).HasMaxLength(15);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.Branch).WithMany(p => p.Suppliers)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Supplier__Branch__22751F6C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}