// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Purchase
{
    public int PurchaseId { get; set; }

    public int BranchId { get; set; }

    public int SupplierId { get; set; }

    public string InvoiceNo { get; set; }

    public DateOnly PurchaseDate { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? Gstamount { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; } = new List<PurchaseDetail>();

    public virtual Supplier Supplier { get; set; }
}