// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Refund
{
    public int RefundId { get; set; }

    public int BookingId { get; set; }

    public DateTime? RefundDate { get; set; }

    public decimal? RefundAmount { get; set; }

    public string RefundMode { get; set; }

    public int? ApprovedBy { get; set; }

    public virtual Booking Booking { get; set; }
}