// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class ServicePricing
{
    public int PricingId { get; set; }

    public int ServiceId { get; set; }

    public int? FromHour { get; set; }

    public int? ToHour { get; set; }

    public string DayType { get; set; }

    public decimal? Price { get; set; }

    public virtual Service Service { get; set; }
}