// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public int BranchId { get; set; }

    public int? ServiceCategoryId { get; set; }

    public string ServiceName { get; set; }

    public string ChargeType { get; set; }

    public decimal? DayPrice { get; set; }

    public decimal? HourPrice { get; set; }

    public decimal? BasePrice { get; set; }

    public decimal? Gstpercent { get; set; }

    public virtual ICollection<BookingService> BookingServices { get; set; } = new List<BookingService>();

    public virtual Branch Branch { get; set; }

    public virtual ICollection<PackageService> PackageServices { get; set; } = new List<PackageService>();

    public virtual ServiceCategory ServiceCategory { get; set; }

    public virtual ICollection<ServicePricing> ServicePricings { get; set; } = new List<ServicePricing>();
}