// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class ServiceCategory
{
    public int ServiceCategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}