// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class StaffAttendance
{
    public int AttendanceId { get; set; }

    public int StaffId { get; set; }

    public DateOnly? AttendanceDate { get; set; }

    public string Status { get; set; }

    public virtual Staff Staff { get; set; }
}