// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class StaffPayment
{
    public int StaffPaymentId { get; set; }

    public int StaffId { get; set; }

    public DateOnly? PaymentDate { get; set; }

    public decimal? Amount { get; set; }

    public string Remarks { get; set; }

    public virtual Staff Staff { get; set; }
}