// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Staff
{
    public int StaffId { get; set; }

    public int BranchId { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string RoleName { get; set; }

    public string SalaryType { get; set; }

    public decimal? SalaryAmount { get; set; }

    public bool? IsActive { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<StaffAttendance> StaffAttendances { get; set; } = new List<StaffAttendance>();

    public virtual ICollection<StaffPayment> StaffPayments { get; set; } = new List<StaffPayment>();
}