// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class StockLedger
{
    public int StockLedgerId { get; set; }

    public int BranchId { get; set; }

    public int ItemId { get; set; }

    public int? RefId { get; set; }

    public string RefType { get; set; }

    public decimal? QuantityIn { get; set; }

    public decimal? QuantityOut { get; set; }

    public DateTime? TransactionDate { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Item Item { get; set; }
}