// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public int BranchId { get; set; }

    public string SupplierName { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Gstnumber { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}